//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMemberInformation
    {
        public int fMId { get; set; }
        public string fName { get; set; }
        public string fNickname { get; set; }
        public System.DateTime fBirthday { get; set; }
        public string fGender { get; set; }
        public string fLivingArea { get; set; }
        public string fNationality { get; set; }
        public string fOccupation { get; set; }
        public string fJLPTLevel { get; set; }
        public string fGoal { get; set; }
        public string fAccount { get; set; }
        public string fPassword { get; set; }
        public string fIdentity { get; set; }
        public string fVerificationCode { get; set; }
        public bool fAlive { get; set; }
        public System.DateTime fRegistrationDatetime { get; set; }
    }
}
